// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLCKXy_XYHCqBdcP6lGIc6J769r6BHEDY',
    appId: '1:1078013869147:web:0aaaa09095a79d9553137e',
    messagingSenderId: '1078013869147',
    projectId: 'fretix-dev-jb',
    authDomain: 'fretix-dev-jb.firebaseapp.com',
    storageBucket: 'fretix-dev-jb.firebasestorage.app',
    measurementId: 'G-2JV92LFFME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmZIXfli3EazsGNPqxJY9AXGgRua-mfxo',
    appId: '1:1078013869147:android:6e1c1ba407016d3953137e',
    messagingSenderId: '1078013869147',
    projectId: 'fretix-dev-jb',
    storageBucket: 'fretix-dev-jb.firebasestorage.app',
  );
}
